Carousel and Navbar fixed
uprm-inso-4117-2021-2022-s2/semester-project-team-11 pull request #8
Opened 2022-04-06 05:01 UTC by peter-santana

Navbar is fixed with routes and carousel is up and working (formatting to make it prettier is tbd)

2022-04-06 22:18 UTC, crobles3 requested changes
can the Navbar be generalized into one component?

2022-04-06 22:18 UTC, crobles3 commented on frontend/src/components/Home/Home.js
> +                                        alt="Third slide"
Change "Third Slide" to "Fourth Slide", just an observation, no big deal.

2022-04-06 22:18 UTC, crobles3 commented on frontend/src/components/Home/Home.js
> +                    <div className="row">
What's the purpose of this div with an empty h2?

2022-04-06 22:18 UTC, crobles3 commented on frontend/src/components/Home/Home.js
> +              <Navbar.Brand href="/">
Either change the width or the height of the navbar brand to auto cause the logo looks a little stretched out. I would recommend letting the width as it is and setting the height to auto.

2022-04-06 23:58 UTC, peter-santana commented
Comments by Christian have been fixed

2022-04-07 00:28 UTC, crobles3 approved these changes

2022-04-07 00:28 UTC, merged